version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-django
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_db_data:/app/db/


  frontend:
    build:
      context: ./frontend
    container_name: frontend-react
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0 
volumes:
  backend_db_data: