# Generated by Django 5.1.2 on 2025-02-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_progress',
            unique_together=set(),
        ),
    ]
