# Generated by Django 5.1.2 on 2025-02-26 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_system', '0002_alter_user_progress_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_progress',
            unique_together={('user', 'Lesson')},
        ),
    ]
