# Generated by Django 5.1.2 on 2025-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_system', '0002_user_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_completion',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
