# Generated by Django 5.1.2 on 2025-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_system', '0003_alter_user_completion_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_progress',
            name='lesson_completion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='user_progress',
            name='module_completion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
