# Generated by Django 5.1.2 on 2025-04-22 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_feature', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz_Progress',
            new_name='Quiz_Tracker',
        ),
        migrations.DeleteModel(
            name='Question_Progress',
        ),
    ]
