# Generated by Django 5.1.2 on 2025-04-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_feature', '0002_rename_quiz_progress_quiz_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('quiz', 'question_number')},
        ),
    ]
